version: "3"

services:
  nginx:
    image: thijsray/ingress
    build:
      context: src/nginx
    networks:
      - nginx-front
      - nginx-back
    ports:
      - "8080:80"
  frontend:
    image: thijsray/frontend
    ports:
      - 80
    build:
      context: src/frontend
    networks:
      - nginx-front
    deploy:
      replicas: 3
  backend:
    image: thijsray/backend
    ports:
      - 80
    build:
      context: src/backend
    networks:
      - nginx-back
      - back-database
    deploy:
      replicas: 3
    environment:
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: "oa16BFoBZXbqKUSynmAGT"
    volumes:
      - /home/thijs/Projects/VU/soco/project/src/backend/src:/var/www/html/api
  database:
    image: postgres:15.1-alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: "oa16BFoBZXbqKUSynmAGT"
    volumes:
      - "database-data:/var/lib/postgresql/data"
    networks:
      - back-database

volumes:
  database-data:

networks:
  nginx-front:
  nginx-back:
  back-database:
