version: "3"

services:
  ingress:
    image: thijsray/ingress
    build:
      context: nginx
    networks:
      - nginx-front
      - nginx-back
    ports:
      - "8080:80"
  frontend:
    image: thijsray/frontend
    ports:
      - 80
    build:
      context: frontend
    networks:
      - nginx-front
    deploy:
      replicas: 3
  backend:
    image: thijsray/backend
    ports:
      - 80
    build:
      context: backend
    networks:
      - nginx-back
      - back-database
    deploy:
      replicas: 3
  database:
    image: postgres:15.1-alpine
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: "oa16BFoBZXbqKUSynmAGT"
    volumes:
      - "database-data:/var/lib/postgresql/data"
    networks:
      - back-database

volumes:
  database-data:

networks:
  nginx-front:
  nginx-back:
  back-database:
