{{ if .Values.backend.autoscaler.enabled }}
# PHP backend autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "socon.fullname" . }}-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "socon.fullname" . }}-backend
  minReplicas: {{ .Values.backend.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.backend.autoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.backend.autoscaler.targetCPUUtilizationPercentage }}
{{ end }}
