apiVersion: v1
kind: Secret
metadata:
  name: {{ include "socon.fullname" . }}-postgres-credentials
type: Opaque
data:
  user: {{ .Values.database.credentials.username | b64enc}}
  password: {{ .Values.database.credentials.password | b64enc}}
  dbname: {{ .Values.database.credentials.dbname | b64enc}}
