{{ if eq .Values.database.storage.storageClassName "local" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "socon.fullname" . }}-postgres-pv
spec:
  storageClassName: {{ .Values.database.storage.storageClassName | quote }}
  capacity:
    storage: {{ .Values.database.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/{{include "socon.fullname" . }}-postgres-pv/"
{{ end }}
