# Postgres service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "socon.fullname" . }}-postgres
  name: {{ include "socon.fullname" . }}-postgres
spec:
  selector:
    app: {{ include "socon.fullname" . }}-postgres
  ports:
    - port: 5432
