# HTTP frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "socon.fullname" . }}-frontend
  name: {{ include "socon.fullname" . }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ include "socon.fullname" . }}-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ include "socon.fullname" . }}-frontend
    spec:
      containers:
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion}}"
        name: {{ include "socon.fullname" . }}-frontend
        imagePullPolicy: "{{ .Values.frontend.image.pullPolicy }}"
        resources: {}
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 5
