{{ if .Values.frontend.autoscaler.enabled }}
# HTTP frontend autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "socon.fullname" . }}-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "socon.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.frontend.autoscaler.targetCPUUtilizationPercentage }}
{{ end }}
