apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: basic-webserver
  name: basic-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: basic-webserver
    spec:
      containers:
      - image: kicbase/echo-server:1.0
        name: echo-server
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: basic-webserver
  name: basic-webserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: basic-webserver
  type: LoadBalancer
status:
  loadBalancer: {}
