# Bootstrap a self signed root cert
{{ if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "socon.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
# Create a CA certificate signed by the root cert
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "socon.fullname" . }}-ca-cert
spec:
  isCA: true
  commonName: {{ .Values.certificates.ca_name }}
  secretName: {{include "socon.fullname" . }}-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "socon.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "socon.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: {{include "socon.fullname" . }}-root-secret
{{ end }}
